name = "studylog-ai"
main = "src/worker.ts"
compatibility_date = "2025-03-01"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "STUDYLOG_KV"
id = "982320c4390f411c89f44ba2e539b44a"
